# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/orderdb
quarkus.datasource.db-version=12

# Hibernate
quarkus.hibernate-orm.log.sql=true

# Flyway
quarkus.flyway.migrate-at-start=true

# Swagger
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/openapi

mp.jwt.verify.issuer=order-management
mp.jwt.verify.publickey.algorithm=RS256
smallrye.jwt.sign.key.location=classpath:privateKey-pkcs8.pem
mp.jwt.verify.publickey.location=classpath:publicKey.pem

quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=BearerAuth
quarkus.smallrye-openapi.security-scheme-description=JWT Authentication

quarkus.log.category."io.smallrye.jwt".level=DEBUG
quarkus.log.category."io.quarkus.smallrye.jwt".level=DEBUG

quarkus.elasticsearch.hosts=localhost:9200

quarkus.redis.hosts=redis://localhost:6379